stash_scene = {'id': '3', 'title': 'Sunflower5', 'code': '', 'details': '', 'director': '', 'urls': [], 'date': None,
               'rating100': None, 'organized': False, 'o_counter': 0, 'interactive': False, 'interactive_speed': None,
               'captions': None, 'created_at': '2025-07-31T08:11:05Z', 'updated_at': '2025-08-01T19:49:31Z',
               'last_played_at': None, 'resume_time': 0, 'play_duration': 0, 'play_count': 0, 'play_history': [],
               'o_history': [], 'files': [
    {'id': '3', 'path': '/data/unsorted/Sunflower2.mp4', 'basename': 'Sunflower2.mp4', 'parent_folder_id': '3',
     'zip_file_id': None, 'mod_time': '2013-12-17T17:59:37Z', 'size': 355856562,
     'fingerprints': [{'type': 'oshash', 'value': 'c4f54a04ebd161b2'}, {'type': 'phash', 'value': 'de83a3120f3eb2ac'}],
     'format': 'mp4', 'width': 1920, 'height': 1080, 'duration': 634.57, 'video_codec': 'h264', 'audio_codec': 'mp3',
     'frame_rate': 60, 'bit_rate': 4486293, 'created_at': '2025-07-31T08:11:05Z', 'updated_at': '2025-07-31T15:17:23Z'},
    {'id': '4', 'path': '/data/bbb_sunflower_1080p_60fps_normal.mp4',
     'basename': 'bbb_sunflower_1080p_60fps_normal.mp4', 'parent_folder_id': '2', 'zip_file_id': None,
     'mod_time': '2013-12-17T17:59:37Z', 'size': 355856562,
     'fingerprints': [{'type': 'oshash', 'value': 'c4f54a04ebd161b2'}, {'type': 'phash', 'value': 'de83a3120f3eb2ac'}],
     'format': 'mp4', 'width': 1920, 'height': 1080, 'duration': 634.57, 'video_codec': 'h264', 'audio_codec': 'mp3',
     'frame_rate': 60, 'bit_rate': 4486293, 'created_at': '2025-08-01T13:04:32Z',
     'updated_at': '2025-08-01T13:04:32Z'}],
               'paths': {'screenshot': 'http://localhost:9999/scene/3/screenshot?t=1754077771',
                         'preview': 'http://localhost:9999/scene/3/preview',
                         'stream': 'http://localhost:9999/scene/3/stream', 'webp': 'http://localhost:9999/scene/3/webp',
                         'vtt': 'http://localhost:9999/scene/c4f54a04ebd161b2_thumbs.vtt',
                         'sprite': 'http://localhost:9999/scene/c4f54a04ebd161b2_sprite.jpg',
                         'funscript': 'http://localhost:9999/scene/3/funscript',
                         'interactive_heatmap': 'http://localhost:9999/scene/3/interactive_heatmap',
                         'caption': 'http://localhost:9999/scene/3/caption'}, 'scene_markers': [], 'galleries': [],
               'studio': {'id': '1'}, 'groups': [], 'tags': [], 'performers': [], 'stash_ids': [], 'sceneStreams': [
    {'url': 'http://localhost:9999/scene/3/stream', 'mime_type': 'video/mp4', 'label': 'Direct stream'},
    {'url': 'http://localhost:9999/scene/3/stream.mp4?resolution=ORIGINAL', 'mime_type': 'video/mp4', 'label': 'MP4'},
    {'url': 'http://localhost:9999/scene/3/stream.mp4?resolution=FULL_HD', 'mime_type': 'video/mp4',
     'label': 'MP4 Full HD (1080p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mp4?resolution=STANDARD_HD', 'mime_type': 'video/mp4',
     'label': 'MP4 HD (720p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mp4?resolution=STANDARD', 'mime_type': 'video/mp4',
     'label': 'MP4 Standard (480p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mp4?resolution=LOW', 'mime_type': 'video/mp4',
     'label': 'MP4 Low (240p)'},
    {'url': 'http://localhost:9999/scene/3/stream.webm?resolution=ORIGINAL', 'mime_type': 'video/webm',
     'label': 'WEBM'},
    {'url': 'http://localhost:9999/scene/3/stream.webm?resolution=FULL_HD', 'mime_type': 'video/webm',
     'label': 'WEBM Full HD (1080p)'},
    {'url': 'http://localhost:9999/scene/3/stream.webm?resolution=STANDARD_HD', 'mime_type': 'video/webm',
     'label': 'WEBM HD (720p)'},
    {'url': 'http://localhost:9999/scene/3/stream.webm?resolution=STANDARD', 'mime_type': 'video/webm',
     'label': 'WEBM Standard (480p)'},
    {'url': 'http://localhost:9999/scene/3/stream.webm?resolution=LOW', 'mime_type': 'video/webm',
     'label': 'WEBM Low (240p)'}, {'url': 'http://localhost:9999/scene/3/stream.m3u8?resolution=ORIGINAL',
                                   'mime_type': 'application/vnd.apple.mpegurl', 'label': 'HLS'},
    {'url': 'http://localhost:9999/scene/3/stream.m3u8?resolution=FULL_HD',
     'mime_type': 'application/vnd.apple.mpegurl', 'label': 'HLS Full HD (1080p)'},
    {'url': 'http://localhost:9999/scene/3/stream.m3u8?resolution=STANDARD_HD',
     'mime_type': 'application/vnd.apple.mpegurl', 'label': 'HLS HD (720p)'},
    {'url': 'http://localhost:9999/scene/3/stream.m3u8?resolution=STANDARD',
     'mime_type': 'application/vnd.apple.mpegurl', 'label': 'HLS Standard (480p)'},
    {'url': 'http://localhost:9999/scene/3/stream.m3u8?resolution=LOW', 'mime_type': 'application/vnd.apple.mpegurl',
     'label': 'HLS Low (240p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mpd?resolution=ORIGINAL', 'mime_type': 'application/dash+xml',
     'label': 'DASH'},
    {'url': 'http://localhost:9999/scene/3/stream.mpd?resolution=FULL_HD', 'mime_type': 'application/dash+xml',
     'label': 'DASH Full HD (1080p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mpd?resolution=STANDARD_HD', 'mime_type': 'application/dash+xml',
     'label': 'DASH HD (720p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mpd?resolution=STANDARD', 'mime_type': 'application/dash+xml',
     'label': 'DASH Standard (480p)'},
    {'url': 'http://localhost:9999/scene/3/stream.mpd?resolution=LOW', 'mime_type': 'application/dash+xml',
     'label': 'DASH Low (240p)'}]}
